### ISSUE TITLE
Standard instruction text in "keySignature" is misleading

### ISSUE THREAD

**Issue by joelrust** [artusiinc/issues#10]
Firstly, these standard instruction texts are helpful but the first time I got one I was surprised! If they're intended to be there in lieu of an instructor providing their own, maybe it could be "pre-loaded" into the section editor?

So, if they are intended, this one assumes the key signatures will be major:
![image](https://user-images.githubusercontent.com/35672157/35744437-5f3bd7ce-080e-11e8-948f-d4a7d10e6471.png)

Perhaps, in order to foolproof the exercise, the major/minor choice could be displayed elsewhere?

**Comment by mscuthbert** [comment]
Yes -- this is a known issue on our list -- basically there is a set of boilerplate instructions but they're set up to describe the default options (for instance, if you choose "Minor" for key signatures, it will still tell you to use capital letters as if they were key signatures) -- we will be making the instructions dynamic according to the rules set up very soon.

**Comment by ryaanahmed** [comment]
Fixed via addition of dynamic instructions.
