### ISSUE TITLE
Harmonic interval ear training examples only show one note

### ISSUE THREAD

**Issue by joelrust** [artusiinc/issues#2]
![harmonic interval examples](https://user-images.githubusercontent.com/35672157/35313369-f333e760-008d-11e8-99e2-9de7c6084dfb.png)

**Comment by mscuthbert** [comment]
It is an ear training exercise -- when you click the score fragment or in the box you'll hear both notes.  Instructors can click "show second note" when defining the assignment to make it an old-school written exercise.

**Comment by joelrust** [comment]
That makes sense. One thing that could be useful: when the interval's been identified correctly, the second note could appear on the staff (to reinforce the interval ID training).

**Comment by ryaanahmed** [comment]
Good idea! We could also see if it's possible to make the "show second note" vs. not thing more obvious to instructors somehow.

**Comment by mscuthbert** [comment]
Great idea -- it's on our Todo list now!

**Comment by mscuthbert** [comment]
Fixed.  Thanks for the suggestion

**Comment by mscuthbert** [comment]
btw -- note is not restored when answers are reloaded.  To me, not a big deal, but we can fix that if it is -- takes a small fix into something more complicated.
