### ISSUE TITLE
Chord creation in inversion

### ISSUE THREAD

**Issue by cbmajor7** [artusiinc/issues#25]
In chord creation, I think it would be helpful to have the option for students to be given an inversion of a chord (especially with the ROMAN option) for students to build in the proper order.

**Comment by mscuthbert** [comment]
This can be done -- give as a chord option I6 or ii65 and it will require the inversion to be right.  There are a number of exercises using this available in Artusi Content to steal from.  :-)

**Comment by cbmajor7** [comment]
Wonderful! Thanks! I'll check it out!
