### ISSUE TITLE
Changing starting note on chord creation in default view

### ISSUE THREAD

**Issue by cbmajor7** [artusiinc/issues#27]
On chord creation in default view, students have the ability to change the given note with accidentals. Though some instructors might want that to be an option, I think it's much better to keep that note fixed.

**Comment by mscuthbert** [comment]
Are you talking about chord creation where one note is given such as root, third, fifth, or seventh?  If so, that's definitely a bug.

**Comment by cbmajor7** [comment]
Yes, that's right. If you click on the first note, you can click an accidental to change it.

**Comment by mscuthbert** [comment]
Fixed in the system -- to go up in an hour or so.

**Comment by cbmajor7** [comment]
Awesome! It's not mentioned in the issue, but intervals also suffers from
this issue.

**Comment by mscuthbert** [comment]
yep -- we checked that editors did not change the note step (A,B,C,D, etc.) of "uneditable" notes, but our system was lacking checks on changing accidentals, "class" (note vs. chord vs. rest), or duration.  These are all fixed -- last chance for creative students to solve a second species by turning the c.f. into all rests is GONE!  :-)
