### ISSUE TITLE
'Problem Set 20: Four Part Writing Practice' is giving strange results

### ISSUE THREAD

**Issue by joelrust** [artusiinc/issues#3]
![ps20](https://user-images.githubusercontent.com/35672157/35473971-b5011de4-0355-11e8-9fee-55375a684444.png)
The exercise loaded like this, EXCEPT for the top left exercise, which I completed – and it found errors with.

**Comment by mscuthbert** [comment]
Thanks for the update -- @ryaanahmed -- I think we're loading the answers from the wrong seed -- this was already identified as a possible issue (see 92 above) but it appears to be more than just theoretical

**Comment by ryaanahmed** [comment]
Definitely that. Taking a look at it now.

**Comment by ryaanahmed** [comment]
@joelrust This issue should be resolved now—could you check if you're still seeing it before I close this out?

**Comment by joelrust** [comment]
Looks resolved to me!
