### ISSUE TITLE
No assignment by that number

### ISSUE THREAD

**Issue by cbmajor7** [artusiinc/issues#37]
This warning happens after I copied in an assignment for a four-part harmonization, entered in music, and then hit 'check.'

**Comment by ryaanahmed** [comment]
Thanks for this report: for some of our more complex section types (like chord progressions), we do checking on the server. It looks like server-side checking for those sections is broken within the section editor. We'll get that fixed ASAP.

By the way, checking _is_ working fine within the bank-level preview, so a workaround for now is to save the section and then preview it within the whole assignment.

**Comment by ryaanahmed** [comment]
Fixed in our next release (later this week)!
