### ISSUE TITLE
Cad 6/4 notation

### ISSUE THREAD

**Issue by cbmajor7** [artusiinc/issues#39]
Under the music in a R.N. realization, the Cad 6/4 just looks like Cad 6/4. For those that want it displayed as V64, usually this is V64 with horizontal lines on the 64 to a 53. Is this possible on the score?

**Comment by mscuthbert** [comment]
We're going to have the "Cad 6/4" under the score bug fixed very soon.  The lines are unfortunately much harder to draw under the score -- this might take a bit longer.

**Comment by mscuthbert** [comment]
Issue #38 will be fixed when this is fixed.  Basically the notation currently allowed within a score is much more limited than in general HTML.  Right now, displaying something is better than nothing, but will be working on making the two equal.

**Comment by mscuthbert** [comment]
Fixed in next release (this week)
