### ISSUE TITLE
Going to "Section Editor" via "Bank Editor" causes a server error

### ISSUE THREAD

**Issue by joelrust** [artusiinc/issues#4]
In "Bank Editor," pressing "Add New Section" and then choosing a section type causes a "Server Error (500)." (Doesn't occur if approached directly from the "Instructor Tools" page.)

**Comment by mscuthbert** [comment]
Message already received from our automated Bat-Signal and i'm on it.  Sorry for the inconvenience.

**Comment by mscuthbert** [comment]
This should all be fixed now -- had some comparisons not working for assignments with no start times and newly created sectionInfo objects.

**Comment by joelrust** [comment]
Thanks! It's working now.

**Comment by mscuthbert** [comment]
btw -- all the instructor pages should load much faster now.
