### ISSUE TITLE
Harmonic rhythm

### ISSUE THREAD

**Issue by cbmajor7** [artusiinc/issues#40]
Is it possible to have different harmonic rhythms in the chord progression exercises? As is, I believe every chord takes up an entire 2/4 measure, but it'd be great to have a quarter note pulse in a 4/4 measure, or variable harmonic rhythms.

**Comment by mscuthbert** [comment]
Put the number of quarter notes you want a chord to last in brackets after the chord name.  For instance:  I[1]-V[1]-I[2]  For eighth notes you can write [0.5].  See https://www.artusi.xyz/assignments/1374/artusi_liii_any_cl014_4-any/

**Comment by mscuthbert** [comment]
Feel free to reopen if more help is needed

**Comment by mscuthbert** [comment]
Coming soon!

**Comment by mscuthbert** [comment]
Ah! yes -- it's in there, but not yet documented;  start with the time signature followed by two equals: "4/4==I[1]-V[1]-I[2]"

Again, this is pretty advanced stuff, but worth knowing!
