### ISSUE TITLE
1st species interval labels

### ISSUE THREAD

**Issue by cbmajor7** [artusiinc/issues#43]
Even though I checked the box to require labels for intervals in 1st species counterpoint, there is no where to add them. Earlier when I tried it, I had empty text boxes below the music, but I couldn't write in them. It would also be nice to put these boxes in between the staves as is normal practice.

**Comment by cbmajor7** [comment]
From what I can tell, this still isn't working. My goal is to start counterpoint next week, and it'd be great to have these interval labels working. Is there a timeline for getting this to work?

**Comment by mscuthbert** [comment]
We fixed this offline.  Please feel free to reopen if it's still an issue.  Best, Myke
