### ISSUE TITLE
1st species erase note

### ISSUE THREAD

**Issue by cbmajor7** [artusiinc/issues#50]
When writing first species, if I get in a corner and have to rewrite a lot of the exercise, it would be nice to delete all of the offending notes, but there's no way to do that that I can tell. Otherwise, the error detector really flips out as all the errors caused by the new notes and the old ones that shouldn't be there distract from the real issues.

**Comment by mscuthbert** [comment]
good idea.

**Comment by mscuthbert** [comment]
We have switched First Species to require a manual "CHECK" button which fixes this issue -- some profs eventually want a maximum on number of checks and we're working on that.
