### ISSUE TITLE
Change assignment type

### ISSUE THREAD

**Issue by cbmajor7** [artusiinc/issues#52]
It would be nice to be able to modify the assignment type from a problem set to an in-class exercise or quiz (e.g.). That way you could duplicate an assignment you've made, modify it, and then use it as in-class exercise before the assignment is given as preparation.

**Comment by mscuthbert** [comment]
I believe that you can do this -- I've done this many times in my classes.  There is a pull down box in the edit assignment menu for this:


<img width="403" alt="screen shot 2019-01-15 at 15 50 18" src="https://user-images.githubusercontent.com/3521479/51209043-4a021400-18dd-11e9-9a15-04a1bd46f32f.png">

**Comment by cbmajor7** [comment]
Right! I see it now! Sorry...still learning the system!

**Comment by mscuthbert** [comment]
No apologies at all! :-)
