### ISSUE TITLE
Chord ID - only in bass clef

### ISSUE THREAD

**Issue by joelrust** [artusiinc/issues#6]
Chord ID only uses the bass clef, even when inappropriate for the chord. (Here, the 'chords' options were: D5 F5 A5, D5 F#5 A5)
![image](https://user-images.githubusercontent.com/35672157/35604250-662cbc48-060f-11e8-89a7-d2fc17cd8f5a.png)

**Comment by mscuthbert** [comment]
Good catch -- I had only done bass clef chords until now.  Feature added!
