### ISSUE TITLE
First species grading

### ISSUE THREAD

**Issue by cbmajor7** [artusiinc/issues#71]
The system seems to not be grading first species counterpoints. When I open an assignment a student has completed, it tells me it is incomplete (the portion that is counterpoint is considered incomplete).  Also, the grade does not reflect that students have completed any of the exercises. If I want to see instructor feedback, I cannot even do that without clicking on one of the notes the student has provided. Here's an example:
https://www.artusi.xyz/assignments/1867/university-of-mary-hardin-baylor_music-theory-2_sp/?seed=56691&forUser=550

**Comment by lacourd** [comment]
We've just gotten to counterpoint in my Theory I class and I'm having this same issue.

**Comment by mscuthbert** [comment]
Apologies -- a tiny bug seems to have spread with new browser versions.  Deployed a fix and all should be working now.  We've been working on a brand-new counterpoint checking system that is almost complete and will be far more sensitive to how students make errors.  We plan to deploy it very soon, but this was a hotfix that I was finally able to replicate and patch.  Thank you both!
