### ISSUE TITLE
Writing Roman numerals

### ISSUE THREAD

**Issue by lacourd** [artusiinc/issues#75]
I'm looking for a way to have students practice simply voicing chords in Artusi using 4-part harmony, hoping to check spacing as well as correct notes given a Roman numeral and figured bass label.

I tried using the chordProgressions section and then listing the progressions as simply single chords, but that I keep getting a ZeroDivisionError ('division by zero'). My work around is to have two-chord progressions that repeat the same Roman numeral, since I assume the main problem is that the program is trying to check voice-leading, which is impossible given a single chord.

**Comment by lacourd** [comment]
Running into further issues with chordProgressions. Example:
Program asks for ii/o7 in eb minor. Student inputs the notes F, Ab, Cb, Eb. Program returns:
-Your progression is missing the root in m. 1.
-Your progression is missing the third in m. 1.
-Your progression is missing the fifth when it is required in m. 1.
-Your chord in m. 1 is in the wrong inversion

Similar sorts of errors are appearing when asked for i64 in minor keys. Am I inputting the chord symbols incorrectly? They are rendering in the way I would expect, but since I can't see under the hood I'm not sure how Artusi is interpreting the language.

**Comment by lacourd** [comment]
I'll add that for the supertonic seventh chord, the issue doesn't seem to arise if the specified key is A minor (although the second inversion tonic triad issue still appears).

**Comment by mscuthbert** [comment]
Thanks for the great -- if unexpected -- use of the system.  Single-chord "ChordProgessions" now work as expected.

Is the ii/o7 working for you now?

**Comment by lacourd** [comment]
Haven’t had any additional trouble with the ii/o7. Thanks for the follow-up and fix!
