### ISSUE TITLE
Pseudo-random generation

### ISSUE THREAD

**Issue by cbmajor7** [artusiinc/issues#77]
Imagine an assignment with three possible chord progressions:
i-V-i
ii/o65-V
VI-iv-V
Currently, there's no way of ensuring students will do one of each (if I set # of problems to 3). In other words, random generation may create all three of the first in different keys or two of the first and one of the third while missing the second. It would be great to have an option where every possible chord progression would be chosen first without recycling it until all have been gone through at least once. Basically, this would be a random selection without replacement. If you want to force this, you need to have three separate sections, with new headers and instructions, which can look a bit clunky.

**Comment by ryaanahmed** [comment]
@cbmajor7 -- this is actually how the chord progressions module already works! It does a random choice without duplicates until it exhausts all possibilities, and then resets. We'll add this to the list for instructor documentation.
